config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  root to: "usr#index"
  resources :sessions
  resources :usrs
  resources :tasks
  # root 'tasks#index'

  # root 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :usrs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :usr
  validates :name, presence: true
  validates :content, presence: true
  validates :content, length: {minimum: 2, maximum: 20}
  validates_presence_of :usr_id
  # validate :start_datetime_cannot_be_later_than_end_datetime
  enum priority: [:low, :medium, :hight]
  # private
  # def start_datetime_cannot_be_later_than_end_datetime
  #   if start_date > end_date
  #     errors.add(:start_datetime, "Can not be set after the end date and time")
  #   end
 
  # end
  paginates_per 3

  def self.search(terms)
    if terms
      where('name LIKE ?, "#%{terms}"')
    else
      order('id desc')
  end
  end 
end

app/models/usr.rb
class Usr < ApplicationRecord
    has_many :tasks
    validates :name, presence: true, length: {maximum: 40}
   validates :email, presence: true, length: {maximum: 200},format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
   before_validation { email.downcase! }
   has_secure_password
   validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/admin/usrs_controller.rb
class Admin::UsrsController < ApplicationController
    before_action :set_usr, only: [:show, :edit, :update, :destroy]
    before_action :only_admin_view_other_users, only: [:index]
    def index
        @usrs=Usr.all
    end
    def show
    end
  
    # GET /usrs/new
    def new
      @usr = Usr.new
    end
  
    # GET /usrs/1/edit
    def edit
    end
  
    # POST /usrs
    def create
      @usr = Usr.new(usr_params)
  
      if @usr.save
        redirect_to @usr, notice: 'Usr was successfully created.'
      else
        render :new
      end
    end
  
    # PATCH/PUT /usrs/1
    def update
      if @usr.update(usr_params)
        redirect_to @usr, notice: 'Usr was successfully updated.'
      else
        render :edit
      end
    end
  
    # DELETE /usrs/1
    def destroy
      @usr.destroy
      redirect_to usrs_url, notice: 'Usr was successfully destroyed.'
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_usr
        @usr = Usr.find(params[:id])
      end
      def current_usr
        @current_usr ||= Usr.find_by(id: session[:usr_id])
      end
      # Only allow a trusted parameter "white list" through.
      def usr_params
        params.require(:usr).permit(:name, :email, :password)
      end
      def only_admin_view_other_users
        if current_usr && current_usr.role != "admin"
          redirect_to admin_usrs_path, notice: "only admin user can access this page"
        end
      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    require 'sessions_helper.rb'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
        def index
          if user_signed_in?
            redirect_to blogs_path
          else
            redirect_to new_user_session_path
          end
        end
      
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private
    def sign_up_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    def account_update_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    usr = Usr.find_by(email: params[:session][:email].downcase)
    if usr && usr.authenticate(params[:session][:password])
      session[:usr_id] = usr.id
      redirect_to tasks_path(usr.id)
    else
      flash.now[:danger] = 'Login failed'
      render 'new'
    end
  end
  def destroy
    session.delete(:usr_id)
    flash[:notice] = 'You logged out'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # before_action :authenticate_usr!
  # before_action :logged_in
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  def index
    if  params[:sort_expired]
      @tasks = Task.order('end_date DESC').page(params[:page])
    elsif params[:sort_priority] 
      @tasks = Task.order('priority DESC').page(params[:page])
    elsif params[:terms]
      @tasks = Task.where('content like ? or status like ?', "%#{params[:terms]}%", "%#{params[:terms]}%").order('id ASC').page(params[:page])
    else
      @tasks = Task.order('created_at DESC').page(params[:page])
    end
  end

  def search
    @task=task.search([:search])
  end

  # GET /tasks/1
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = Task.create(task_params)

    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:name, :content, :status, :priority, :usr_id, :terms, :start_date, :end_date)
    end
end

app/controllers/usrs_controller.rb
class UsrsController < ApplicationController
  before_action :set_usr, only: [:show, :edit, :update, :destroy]

  # GET /usrs
  def index
    @usrs = Usr.all
  end

  # GET /usrs/1
  def show
  end

  # GET /usrs/new
  def new
    @usr = Usr.new
  end

  # GET /usrs/1/edit
  def edit
  end

  # POST /usrs
  def create
    @usr = Usr.new(usr_params)

    if @usr.save
      redirect_to @usr, notice: 'Usr was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /usrs/1
  def update
    if @usr.update(usr_params)
      redirect_to @usr, notice: 'Usr was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /usrs/1
  def destroy
    @usr.destroy
    redirect_to usrs_url, notice: 'Usr was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usr
      @usr = Usr.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def usr_params
      params.require(:usr).permit(:name, :email, :password, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_usr
        @current_usr ||= Usr.find_by(id: session[:usr_id])
      end
      def logged_in?
        current_usr.present?
      end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/usrs_helper.rb
module UsrsHelper
end

app/views/admin/usrs/_form.html.erb
<%= form_with(model: usr, local: true) do |form| %>
  <% if usr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usr.errors.count, "error") %> prohibited this usr from being saved:</h2>

      <ul>
      <% usr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fielder">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="fielder">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control" %>
  </div>
  <div class="form-group">
   <%= form.label :UserType %>
   <%= form.select(:role, options_for_select([['User','User'],['Admin','Admin']])) %>
  </div>

  <div class="fielder">
    <%= form.label :password %>
    <%= form.text_field :password, class:"form-control" %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/admin/usrs/edit.html.erb
<h1>Editing Usr</h1>

<%= render 'form', usr: @usr %>

<%= link_to 'Show', @usr %> |
<%= link_to 'Back', admin_usrs_path %>

app/views/admin/usrs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usrs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Task</th>
      <th>User type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usrs.each do |usr| %>
      <tr>
        <td><%= usr.name %></td>
        <td><%= usr.email %></td>
        <td><%= usr.tasks.count %></td>
        <td><%= usr.role %></td>
        <td><%= link_to 'Show', admin_usr_path(usr) %></td>
        <td><%= link_to 'Edit', edit_admin_usr_path(usr) %></td>
        <td><%= link_to 'Destroy', usr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usr', new_admin_usr_path %>

app/views/admin/usrs/new.html.erb
<div class ="controler">
<h1>New User</h1>

<%= render 'form', usr: @usr %>

<%= link_to 'Back', admin_usrs_path %>
</div>

app/views/admin/usrs/show.html.erb
<div class = "bodyp">
<div class = "bodypp">
<p> <h2> Tasks Submitted By This User</h2>
</div>
<% @usr.tasks.each do |task| %>
<ul>
<li class = "user-tasks">
 Name:<%= task.name + '       ' %> <br/>Content:<%= task.content %>
</li>
</ul>
<% end %>
</p>

<%= link_to 'Edit', edit_admin_usr_path(@usr), class:"btn btn-outline-primary" %> |
<%= link_to 'Back', admin_usrs_path, class:"btn btn-outline-primary" %>

</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Everleaftasks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
  <nav class="navbar navbar-expand-sm bg-secondary navbar-dark">
   <div class="container-fluid">
  <a class="navbar-brand" href="#"><div class="style">Everleaf CO.LTD</div>
<% flash.each do |key, value| %>
   <%= content_tag(:div, value, class: "#{key}") %>
 <% end %>
 <% if logged_in? %>
   <%= link_to 'Home', tasks_path,class:"btn btn-outline-primary" %>
   <%= link_to "Profile", usr_path(current_usr.id), class:"btn btn-outline-primary" %>
   <%= link_to "Logout", session_path(current_usr.id), method: :delete, class:"btn btn-outline-primary" %>
   <%= link_to 'User list', usrs_path, class:"btn btn-outline-primary" if logged_in? %>
   <%= link_to 'Admin list', admin_usrs_path, class:"btn btn-outline-primary" if logged_in? %>
 <% else %>
   <%= link_to "Sign up", new_usr_path, class:"btn btn-outline-primary" %>
   <%= link_to "Login", new_session_path, class:"btn btn-outline-primary" %>
 <% end %>


    <%# <%= yield %>  
    </div>
</nav>
    <%= yield %> <br>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      </body>
</html>

app/views/tasks/_form.html.erb
<div class="form22">
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_field :content, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :stutus %>
    <%= form.text_field :status, class:"form-control" %>
  </div>

  <div class="form-group">
  <%= form.label :priority %>
    <%= form.radio_button :priority, 'low' %> low  <%= form.radio_button :priority, 'medium' %> medium <%= form.radio_button :priority, 'hight' %> high
  </div>

  <div class="form-group">
   
    <%= form.hidden_field :usr_id %>
  </div>

  <div class="form-group">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="form-group">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>
    <div class="field">

    <%= form.hidden_field :usr_id, value: current_usr.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="container">
<div class="menu">
<ul class="list">
<li><%= link_to 'New Task', new_task_path %></li>
<li><%= link_to 'sort expiration', tasks_path(sort_expired: 'true') %></li>
<li><%= link_to 'sort by priority', tasks_path(sort_priority: 'true') %></li>
</div>
<div class="show">
<%= form_tag(tasks_path, method: :get) do  %>
             <div class="form-inline my-2 my-lg-0">
               <%= text_field_tag :terms, params[:terms], placeholder: "search by content" %>
               <%= submit_tag 'Search', name:nil %>
             </div>
           <% end %>
<p id="notice"><%= notice %></p>
<h1><%= t('view.ALL TASKS')%></h1>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Status</th>
      <th>Priority</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3">Buttons</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.content %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= task.start_date %></td>
        <td><%= task.end_date %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @tasks %>
</div>
</div>

<br>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @task.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @task.end_date %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/usrs/_form.html.erb
<%= form_with(model: usr, local: true) do |form| %>
  <% if usr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usr.errors.count, "error") %> prohibited this usr from being saved:</h2>

      <ul>
      <% usr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fielder">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="fielder">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="fielder">
    <%= form.label :UserType %>
    <%= form.text_field :role , class:"form-control", disabled: (true unless current_usr and current_usr.role == "admin") %>
  </div>

  <div class="fielder">
    <%= form.label :password %>
    <%= form.text_field :password, class:"form-control" %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/usrs/edit.html.erb
<h1>Editing Usr</h1>

<%= render 'form', usr: @usr %>

<%= link_to 'Show', @usr %> |
<%= link_to 'Back', usrs_path %>

app/views/usrs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usrs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>User Type</th>
    </tr>
  </thead>

  <tbody>
    <% @usrs.each do |usr| %>
      <tr>
        <td><%= usr.name %></td>
        <td><%= usr.email %></td>
        <td><%= usr.role %></td>
        <td><%= usr.password %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usr', new_usr_path %>

app/views/usrs/new.html.erb
<div class ="controler">
<h1>New User</h1>

<%= render 'form', usr: @usr %>

<%= link_to 'Back', usrs_path %>
</div>

app/views/usrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @usr.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usr.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @usr.password %>
</p>

<%= link_to 'Edit', edit_usr_path(@usr) %> |
<%= link_to 'Back', usrs_path %>